#!/bin/bash
# Default XAMPP installation path
XAMPP=/opt/lampp

if [[ $1 == 'start' || $1 == 'stop' || $1 == 'restart' ]]; then
	sudo $XAMPP/lampp $1
elif [[ $1 == 'panel' ]]; then
	sudo $XAMPP/manager-linux-x64.run
elif [[ $1 == 'help' ]]; then
	printf "Usage:
	xampp on\t: To turn on XAMPP modules
	xampp re\t: To restart XAMPP modules
	xampp off\t: To turn off XAMPP modules
	xampp help\t: To show this help\n"
else
	printf "Too few or invalid argument!"
fi